import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import available Google fonts
import "./globals.css";

// Specify the font weight along with subsets
const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
  weight: "400", // Add weight property (choose based on your needs)
});

export const metadata: Metadata = {
  title: "Ameer Hamza Pizza",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
